from typing import Protocol, runtime_checkable
from .models import Formula, ConsolidationResult


@runtime_checkable
class MemoryStore(Protocol):
    async def write(self, namespace: str, key: str, value: dict, ttl_hours: float | None = None) -> None: ...
    async def read(self, namespace: str, key: str) -> dict | None: ...
    async def search(self, namespace: str, query: str, top_k: int = 5) -> list[dict]: ...
    async def delete(self, namespace: str, key: str) -> None: ...


@runtime_checkable
class FormulaStore(Protocol):
    def lookup(self, agent_role: str, task: str) -> Formula | None: ...
    def get(self, formula_id: str, version: int | None = None) -> Formula | None: ...
    def propose(self, formula: "Formula") -> str: ...
    def list_active(self, agent_role: str) -> list[Formula]: ...


@runtime_checkable
class ConsolidationWorker(Protocol):
    async def run_pass(self, namespace: str) -> ConsolidationResult: ...
